### ISSUE TITLE
possibly incorrect model of differential characteristics generated by CASCADA

### ISSUE THREAD

**Issue by PolikarpovSV** [ranea/CASCADA#3]
Hello,
we tried to find the differential characteristics for the PRF pCollapser_32bit, but the found characteristics look wrong. 
The PRF in each round contains 32 sboxes running in parallel. Each sbox has in/out lenght = 4 bit. 
The source code of the test PRF is located at: github.com/pruvad/testrep_ibtks [pcollapser_32bit.zip](https://github.com/ranea/CASCADA/files/10569968/pcollapser_32bit.zip)

Founded weights with CASCADA (for 2 rounds): 
2 : Ch(w=18.00, id=0 0 0 7 0 0 0 7, od=0 0 0 0 0 0 0 0) - wdt model
2 : Ch(w=8, id=0 0 8 8 0 0 0 0, od=0 0 0 0 0 0 0 0) - weak model (num of the active sbox) 

The obtained characteristics show the presence of collisions, which should be detected with 2^18 input differences (or 2^16 for weak model).
Checking the correctness of the obtained characteristics showed that collisions are not detected with 2^22 input differences. An example of a function for checking collisions is given in the specified source code: pcollapser_32bit.pcollapserEncryption.validateXorDiff() 

There may be several options here:
1. We have made a mistake somewhere or are misinterpreting the results (and we apologize in advance if this is the case).
2. The model for the differential characteristics is not formed correctly by CASCADA.

**Comment by ranea** [comment]
Can you run again the search with the additional `round_based_ch_search`  parameters

 - `extra_chfinder_args = {..., "printing_mode": PrintingMode.WeightsAndSrepr}`
 - `extra_findnextchweight_args = {..., "empirical_weight_options": {"seed": 0}}`
    
and attach here the output?

**Comment by ranea** [comment]
I don't know the structure of the PRF pCollapser_32bit, but I think that the main problem (which is very common) is that the differences within the characteristics are highly dependent (and thus the Markov cipher assumption doesn't hold).

If you compute the empirical weights during the search by enabling `empirical_weight_options`

```
round_based_ch_search(..., 
    extra_chfinder_args={..., "printing_mode": PrintingMode.WeightsAndSrepr}
    extra_findnextchweight_args={..., "empirical_weight_options":{"C_code": True}
)
```

you will see that the search will discard these invalid characteristics. 

I did a quick search for 1 and 2 rounds. For 1 round valid characteristics were found (and you could test those). But for 2 rounds the first characteristics that I found were invalid

```
Invalid characteristic found | Ch(w=16, ew=inf, id=0 0 0 0 0 0 8 8, od=0 0 0 0 0 0 0 0)
Invalid characteristic found | Ch(w=16, ew=inf, id=0 0 0 0 0 0 8 8, od=0 0 0 0 0 0 0 0)
Invalid characteristic found | Ch(w=16, ew=inf, id=8 8 0 0 0 0 0 0, od=0 0 0 0 0 0 0 0)
```

You could try to run the search for a long time to see if you are lucky to find a valid characteristic.

Regarding the characteristics found with the weak model, these will not be valid as they don't use the details of the S-boxes. You can only use this type of characteristics to provide bounds on the characteristic probability.

Finally, I found a minor bug in the weights stored in WDTModel that I fixed in the last commit.

**Comment by PolikarpovSV** [comment]
thanks for response
> I don't know the structure of the PRF pCollapser_32bit, but I think that the main problem (which is very common) is that the differences within the characteristics are highly dependent (and thus the Markov cipher assumption doesn't hold).

i think it's true - PRF pCollapser consists of pdsbox_func (pseudo-dynamic sbox) - a function that acts like a dynamic sbox in the second round and subsequent rounds (uses control state S)

> If you compute the empirical weights during the search by enabling `empirical_weight_options`
> 
> ```
> round_based_ch_search(..., 
>     extra_chfinder_args={..., "printing_mode": PrintingMode.WeightsAndSrepr}
>     extra_findnextchweight_args={..., "empirical_weight_options":{"C_code": True}
> )
> ```
"printing_mode": PrintingMode.WeightsAndSrepr - option not available (NameError: name 'PrintingMode' is not defined) if run as:

from cascada.differential.difference import XorDiff, RXDiff
from cascada.smt.chsearch import ChModelAssertType, round_based_ch_search
from cascada.primitives import pcollapser_32bit
pcollapser = pcollapser_32bit.pcollapserLWC_32bit
assert_type = ChModelAssertType.ValidityAndWeight
iterator = round_based_ch_search(pcollapser, 2, 4, XorDiff, assert_type, "btor",
extra_chfinder_args={"exclude_zero_input_prop": True, "solver_seed": 0, "printing_mode": PrintingMode.WeightsAndSrepr},
extra_findnextchweight_args={"initial_weight": 0, "empirical_weight_options":{"C_code": True}})
for (num_rounds, ch) in iterator:
     print(num_rounds, ":", ch.srepr())

> 
> you will see that the search will discard these invalid characteristics.
> 
> I did a quick search for 1 and 2 rounds. For 1 round valid characteristics were found (and you could test those). But for 2 rounds the first characteristics that I found were invalid
> 
> ```
> Invalid characteristic found | Ch(w=16, ew=inf, id=0 0 0 0 0 0 8 8, od=0 0 0 0 0 0 0 0)
> Invalid characteristic found | Ch(w=16, ew=inf, id=0 0 0 0 0 0 8 8, od=0 0 0 0 0 0 0 0)
> Invalid characteristic found | Ch(w=16, ew=inf, id=8 8 0 0 0 0 0 0, od=0 0 0 0 0 0 0 0)
> ```
> 
> You could try to run the search for a long time to see if you are lucky to find a valid characteristic.

after some time we found this ch:

2 : Ch(w=16, ew=27, id=8 0 0 0 0 0 0 8, od=0 0 0 0 0 0 0 0)
 
but experimental results :
out diff stats: cnt_eq / cnt_total =  0 / 536870912    
(not found collision for 2^29 samples)
It seems to be an invalid characteristic in both cases.
    
Moreover, we tried option "split_by_max_weight": 8
and found this characteristic:
    
2 : Ch(w=18, ew=10.04, id=0 0 9 0 0 0 9 0, od=0 0 0 0 0 0 0 0)
    
experimental results :
out diff stats: cnt_eq / cnt_total = 0 / 262144
(not found collision for 2^18 samples)
this also seems to be an invalid characteristic
> 
> Regarding the characteristics found with the weak model, these will not be valid as they don't use the details of the S-boxes. You can only use this type of characteristics to provide bounds on the characteristic probability.
> 
> Finally, I found a minor bug in the weights stored in WDTModel that I fixed in the last commit.

thanks for a great tool, we really wanted to confirm the characteristics of our PRF with it

**Comment by ranea** [comment]
> "printing_mode": PrintingMode.WeightsAndSrepr - option not available (NameError: name 'PrintingMode' is not defined) i

You can import it as `from cascada.smt.chsearch import PrintingMode`.



> after some time we found this ch:
> 
> 2 : Ch(w=16, ew=27, id=8 0 0 0 0 0 0 8, od=0 0 0 0 0 0 0 0)
> 
> but experimental results : out diff stats: cnt_eq / cnt_total = 0 / 536870912 (not found collision for 2^29 samples) It seems to be an invalid characteristic in both cases.

I tried to reproduce this result by adapting your code as follows (and using the last commit)

```python
[...]
DIFF_MODEL_TYPE   = 2		# 1 - weak model,  2 - ddt model
[...]
def find_XorDiff_ch():
    pcollapser = pcollapserLWC_32bit
    assert_type = ChModelAssertType.ValidityAndWeight

    # fix input difference to 8 0 0 0 0 0 0 8
    v2c = {Variable("dp0", 4): Constant(0x8, 4), Variable("dp7", 4): Constant(0x8, 4)}
    for i in range(1, 7):
        v2c[Variable(f"dp{i}", 4)] = Constant(0, 4)
    # fix output difference to 0 0 0 0 0 0 0 0
    v2c[Variable("dx176_out", 4)] = Constant(0, 4)
    v2c[Variable("dx195_out", 4)] = Constant(0, 4)
    v2c[Variable("dx218_out", 4)] = Constant(0, 4)
    v2c[Variable("dx241_out", 4)] = Constant(0, 4)
    v2c[Variable("dx264_out", 4)] = Constant(0, 4)
    v2c[Variable("dx287_out", 4)] = Constant(0, 4)
    v2c[Variable("dx310_out", 4)] = Constant(0, 4)
    v2c[Variable("dx332_out", 4)] = Constant(0, 4)

    from cascada.smt.chsearch import PrintingMode

    iterator = round_based_ch_search(pcollapser, 2, 2, XorDiff, assert_type, "btor",
        extra_chfinder_args={"solver_seed": 0, "printing_mode": PrintingMode.WeightsAndSrepr,  "var_prop2ct_prop": v2c},
        extra_findnextchweight_args={"initial_weight": 15, "final_weight": 17,
                                     "empirical_weight_options":{"C_code": True, "num_parallel_processes": 4,
                                                                 "num_input_samples": 2**21, "num_external_samples": 64}})
    for (num_rounds, ch) in iterator:
        print(num_rounds, ":", ch.srepr())
        break

if __name__ == '__main__':
    find_XorDiff_ch()
```

but I am not sure how you got the empirical weight to be 27 as the result I got (with 2^21 inputs and 64 keys) was

```
Current number of rounds: 2
Solving for weight = 15
Solving for weight = 16
Invalid characteristic found | Ch(w=16, ew=inf, id=8 0 0 0 0 0 0 8, od=0 0 0 0 0 0 0 0)
Invalid characteristic found | Ch(w=16, ew=inf, id=8 0 0 0 0 0 0 8, od=0 0 0 0 0 0 0 0)
```

Anyway, the problem I think is the following. If the empirical weight of a characteristic is computed without splitting (and thus without making independence assumption) and it is not infinite, this means that at least one valid input pair (for some random round keys) was found in the empirical weight computation. However, note that in the empirical weight computation the round keys (called in the documentation of `compute_empirical_ch_weight` external samples) are randomly sampled and they do not follow the key-schedule. That is why you can get a characteristic with a valid empirical weight and still not being able to find colissions, as the key schedule is being ignored. When I have some time, I will update the documentation of `compute_empirical_ch_weight` mentioning this problem as it is not clear as of now.

The only way I could see to find collisions using automated methods is to use an approach like the recent paper https://eprint.iacr.org/2022/402 (see Section 4.5, which is actually inspired from https://eprint.iacr.org/2020/632). While this is not explicitly implemented in CASCADA, it can be done (with some effort) by "combining" a `ChFinder` that search for differential characteristics and two `ChFinder` objects with the `algebraic` property that search for the two valid inputs.

**Comment by PolikarpovSV** [comment]
thanks a lot for the advice.

For the empirical weight of differentials, we rechecked the properties and got the conclusion - there is a simple collision, as in the case of two random 32-bit values.
For this we set "**num_input_samples**": 2**32, "**num_external_samples**": 8
(function "`find_XorDiff_ch_we()`" in updated source code)
[pcollapser_32bit_6.02.2023.zip](https://github.com/ranea/CASCADA/files/10664682/pcollapser_32bit_6.02.2023.zip)
Got the following results:
`2 : Ch(w=16, ew=33, id=0 0 8 0 0 0 0 8, od=0 0 0 0 0 0 0 0)`
`2 : Ch(w=16, ew=30.42, id=0 0 0 0 8 0 0 8, od=0 0 0 0 0 0 0 0)`
`2 : Ch(w=16, ew=32, id=0 0 0 0 8 0 0 8, od=0 0 0 0 0 0 0 0)`
The problem here is that the value of the weight `ew` is calculated inaccurately when there are not enough samples.

Moreover, we checked the linear properties (function "`find_Linear_ch()`" in updated source code).
Results for `"num_input_samples": 2**12`
`2 : Ch(w=16, ew=6.286, id=0 0 0 4 0 0 0 c, od=0 0 0 9 0 0 0 9)`
Results for `"num_input_samples": 2**26`
`2 : Ch(w=16, ew=10.77, id=0 0 0 4 0 0 0 c, od=0 0 0 9 0 0 0 9)`

The dependence of the weight value on the number of samples is immediately noticeable.
Additional debug **print** in the `linear/characteristic.py` made it possible to see the weight calculation steps ( for "**num_input_samples**": 2**12):

`num_right_inputs =  2020`
`num_input_samples =  4096`
`inner_pr =  0.4931640625`
`correlation =  0.0136718750`
`weight_ =  6.192645077942395892558030683`

You may notice that the calculation of the weight `ew` also does not take into account the calculation error caused by the limited number of samples. (And the maximum value of the weight `ew` is limited by the value of the samples). It turns out that if you increase / decrease the number of samples, then the calculated value of `ew` will increase / decrease proportionally. Maybe for such a case to display warnings? Or add an estimate of the error in calculating the weight `ew`?

~~In addition, it is not indicated for which probability of success the weight is calculated. Taking the widely used success rate of 97.7%, the weight value `ew` would be calculated as:~~

~~`prop = num_right_inputs / total_inputs`~~
~~`bias = | prop - 1/2 |`~~
~~`ew = -2*log2_(bias)`~~

~~If we make the appropriate changes in src (in the `linear/characteristic.py` , line **259** ):~~

`           weight_ = - abstractproperty.opmodel.log2_decimal(correlation)`
`            bias = correlation/2`
`            weight = - 2*abstractproperty.opmodel.log2_decimal(bias)`



~~we get next results:~~

` num_right_inputs =  33560160` 
` num_input_samples =  67108864` 
` inner_pr =  0.500085353851318359375` 
` correlation =  0.000170707702636718750` 
` weight_ =  12.51618422273574357590835635` 

~~and corrected weight (for "**num_input_samples**": 2**26):~~

` bias =  0.000085353851318359375` 
` weight =  27.03236844547148715181671270`

`2 : Ch(w=16, ew=28.26, id=0 0 0 4 0 0 0 c, od=0 0 0 9 0 0 0 9)`
`6-16:53 | Final weight decreased to 16`

**Comment by PolikarpovSV** [comment]
but, if the weight is understood as a degree for the bias, then the source code is correct

**Comment by ranea** [comment]
> The problem here is that the value of the weight ew is calculated inaccurately when there are not enough samples.

By definition that is the nature of the empirical weight, meaning it is always an approximation unless the number of input samples is equal to the plaintext space.


> Additional debug print in the linear/characteristic.py made it possible to see the weight calculation steps

You can also see this information from the attribute `empirical_data_list` of a characteristic (and you will obtain something like `[EmpiricalWeightData(weight_avg_aux_prs=..., num_aux_weights=..., num_inf_aux_weights=..., num_input_samples=..., ...)]`.

Additionally, the number of samples in the case of linear is computed as
`int(math.ceil(small_ct * p))`, where `small_ct` is a small constant (the number of input bits) and `p = 2 ** (2 * (self.ch_weight + self.ch_model.error()))`. 


> You may notice that the calculation of the weight ew also does not take into account the calculation error caused by the limited number of samples. (And the maximum value of the weight ew is limited by the value of the samples). It turns out that if you increase / decrease the number of samples, then the calculated value of ew will increase / decrease proportionally. Maybe for such a case to display warnings? Or add an estimate of the error in calculating the weight ew?

I don't know how to easily estimate the error between the empirical weight and the true weight (for a fixed key) without sampling the whole space (note that this error is not the same as `ch_model.error()`). 


> but, if the weight is understood as a degree for the bias, then the source code is correct

I am not sure what do you mean by the degree, but for `LinearMask` properties,  the propagation probability is taking as the absolute correlation (and not as the bias or the linear potential, see `LinearMask`).



Thanks for your feedback! You gave me some ideas to extend and clarify the documentation with the questions you raised. If you have more questions, please do, otherwise I'll close this issue.

**Comment by PolikarpovSV** [comment]
thank you very much for the clarification, no more questions
